### PR TITLE
Support multiple name resolution targets

### PR DESCRIPTION
**Pull request by Apanatshka**
This preserves the original behaviour of a single resolution target, while allowing multiple to be shown with a default text derived from the resolution path through `nabl2--editor-resolution-show-all`.

The resolutions are now ordered by path length (smaller first) and path elements (D, then E, then N) to have a deterministic order. See `nabl2-path-gt` and `nabl2-path-elem-gt` for the exact details. 

PR group:
metaborg/spt#23
metaborg/spoofax#38
metaborg/spoofax-eclipse#13
metaborg/nabl#14
metaborg/spoofax-intellij#29

multi-resolution

### CODE REVIEW

**Comment by hendrikvanantwerpen** [comment]
If I understand correctly, you changed Spoofax to show a list of resolution targets if there are multiple? Nice feature to have :). My comments are based on that assumption.

* NaBL2 always returned multiple targets, Spoofax just picked one. I think the list should always be shown, if there are multiple options. So, the flag `nabl2--editor-resolve-show-all` can go, this should be the new -- and better -- behavior.

* Instead of filtering the output of editor resolve (which will fail hard now, since `filter` is used in a `with` clause), I would return different values based on the result. If it is an empty list, fail, if a singleton, just return the target, otherwise return the list of fancy formatted outputs.

* Alternatively, you could always output the fance formatted output, and Spoofax would not show singleton lists, but jump there immediately, which saves case distinctions in the languages.

* Isn't it more sensible to order resolution options by filename and position in the file, instead of the path structure, which is a bit arbitrary? This ordering could also happen on the Spoofax side, I think. Or provide a default strategy in `libspoofax` that languages can use. That way you keep the option to do something fancy yourself (if language semantics justify a certain order, for example).

* Similarly, I don't think printing the path is a very user friendly default. Again a strategy could be to show names and positions in the file, maybe include filenames of there are targets from multiple files. This could be part of libspoofax again, so that it is easy to start using this, but still possible to customize if necessary.

I'm tagging @Gohla, so he can comment on any implications for the Spoofax side.

**Comment by Apanatshka** [comment]
Yeah, I should have written a bit more description along with the PR, but I had to leave immediately after opening these ^^
So to answer your questions: Yes, I've added functionality in Spoofax to show multiple resolution targets in a list. 

- I'm fine with showing the list by default if there's multiple options. I just added the hook in case you wanted to preserve the original behaviour. 
- Yeah, the filter doesn't need to be in there I guess. 
- Spoofax (or rather Eclipse) will already handle a singleton list as a single option with immediate jump. In fact, the standard behaviour is to jump to the first option in the list if you click; and only show the list if you hover. 
- By the time you pass the resolution targets to Spoofax, the path is already gone. While I was testing things I found out that the order of the resolution target was different for different references (resulting in an ambiguous reference resolving to different definitions depending on the location of the reference). That's why I wrote some kind of ordering for paths. I figured if users want to order things differently or write their own labels for the list of targets they would have to reimplement things themselves anyway. 
- I can definitely change the labels to filename+offset based on origins, that does seem like a nicer default.

**Comment by Apanatshka** [comment]
Yay, now the changes are tiny ^^ See https://github.com/metaborg/spoofax/pull/38/commits/c7a630e984e12917911437b53f87fea3bcdac941 for the sorting of resolutions based on origin

**Comment by Apanatshka** [comment]
This is what it looks like now:
multi-resolution

**Comment by hendrikvanantwerpen** [comment]
Yay for tiny changes :)

**Comment by hendrikvanantwerpen** [comment]
Most of the inverse resolution looks okay. I'm wondering about `nabl2--editor-resolve` though. Currently it looks like you want to show resolving references on Ctrl+Click on a declaration. This may be problematic if an AST node is used both as a reference and a declaration. Furthermore, I'm wondering if decl-to-ref under the same UI action as ref-to-decl is not confusing for people? Wouldn't it make more sense to have a separate action (e.g., Ctrl+Shift+Click) for decl to ref, and maybe always show a list in that case, instead of automatically jumping if there is only one option? For ref-to-decl I expect a jump by default, but decl-to-ref I think of as a search. Of course this would require some more changes in Core. What do you think, @Gohla, @Virtlink?

**Comment by hendrikvanantwerpen** [comment]
Given that AST nodes can be used in multiple references, it might be useful (sometimes) to show the namespace in the list of resolved declaration. However, this is formatting that would be supported by the machinery provided by these PRs, right?

**Comment by Virtlink** [comment]
IntelliJ distinguishes between 'Go To Definition' and 'Find Usages', and these actions have their own keyboard shortcuts by default. However, Ctrl+Clicking an identifier performs either of these actions, depending on whether it is a declaration or a reference. I don't know what happens when an identifier is _both_ a declaration and a reference, but I would guess that 'Go To Definition' takes precedence.

**Comment by Apanatshka** [comment]
> Wouldn't it make more sense to have a separate action (e.g., Ctrl+Shift+Click) for decl to ref, and maybe always show a list in that case, instead of automatically jumping if there is only one option?

I can try to find a way to have ctrl+click not resolve to the first option if there are multiple options. I think that's generally better behaviour. Separate action is not necessary IMO, IntelliJ's default behaviour supports that. 
I don't want to go into adding more actions, because that will probably take way more time. Right now the PRs are reasonably small and easy to review. We can put more actions/services on the wishlist (aka issue tracker). 

> [show resolving references on Ctrl+Click on a declaration] may be problematic if an AST node is used both as a reference and a declaration.

Yes, that's true. But is this a likely scenario? Is it useful for anything? If not, then I don't think we need to support it out of the box. People can still write their own `editor-resolve`
(Currently if the reference and declaration live on the same AST node, the reference rule will fire first, and the declaration rule will be ignored then. )

> Given that AST nodes can be used in multiple references, it might be useful (sometimes) to show the namespace in the list of resolved declaration. However, this is formatting that would be supported by the machinery provided by these PRs, right?

Yes, you can write your custom resolution labels to include namespaces. I could even write one of those for NaBL2 as an example. The label shown in the screenshots is the default label derived from origin info; Spoofax core will automatically create and use that when no label is given.

**Comment by Apanatshka** [comment]
> I can try to find a way to have ctrl+click not resolve to the first option if there are multiple options.
I've found the original ticket where they implemented showing multiple hyperlinks in Eclipse (https://bugs.eclipse.org/bugs/show_bug.cgi?id=215473). I cannot find anything about the original plan to be able to configure the default hyperlink that's used when you ctrl+click. I have found the code in the implementation which chooses this though, so I may be able to change it.

**Pull request merged**
