### PR TITLE
Frame API updates & Occurrence generation

### PR DESCRIPTION
**Pull request by vvergu**
This PR contains the following items:

1. Generate transformations to replace identifiers by occurrences in program ASTs.
2. Updates to Frame API

The main contribution is item 1 above. I extended the Nabl2 -> Stratego generator to generate strategies named `nabl2--transform-occurrences`.

Given a NaBL2 rule which matches pattern `P` and stores declarations `D*` and references `R*`, the extended generator emits a rule named `nabl2--transform-occurrences` which matches pattern `P` and emits a term `P'` which has all of `D*` and `R*` replaced by Occurrences. An Occurrences contains the identifier name, the namespace, and the unique position in the AST of the identifier.

This replacement has to happen on NaBL2-side as there is insufficient information in DynSem in the absence of the NaBL2 specification to create Occurrences (specifically, the namespace an identifier pertains to is unknown).

The generated `nabl2--transform-occurrences` rules are not called automatically. To invoke the translation the user has to apply the following transformation:

```
<bottomup(try(preserve-annos(nabl2--transform-occurrences)))> ast
```

### CODE REVIEW

**Comment by vvergu** [comment]
@hendrikvanantwerpen I've updated this PR (commit and description). Please let's discuss steps necessary to merge this into master.

**Comment by hendrikvanantwerpen** [comment]
Okay, some quick questions:
* If you have a rule `[[ Var(x) ^ (s) : ty ]] := Var{x} -> s, ...`, you replace `Var(x)` with `Var(Var{x})`, right?
* If you have a rule `[[ Struct(x, _) ^ (s) : ty ]] := Type{x} <- s, Impl{x} <- s, ...`, what happens? Do you pick a random one, insert a list, or does the transformation crash?
* Should we generate a `nabl2--transform-all-occurrences = bottomup(try(preserve-annos(nabl2--transform-occurrences)))` as well?

**Comment by hendrikvanantwerpen** [comment]
What about the commented code in the frame API? Is this to be restored later, or can it just be removed?

**Comment by vvergu** [comment]
@hendrikvanantwerpen: i've edited your comments above to number the questions.

1. Yes, where `Var{x}` is the occurrence term of the form `Occurrence(namespace, x, term-index)`
2. It picks the first one
3. Yes, we could, i'll update and push now
4. It can be removed

**Comment by Apanatshka** [comment]
It may be better to just define `nabl2--transform-all-occurrences = bottomup(try(preserve-annos(nabl2--transform-occurrences)))` in the nabl2.runtime library, along with `nabl2--transform-occurrences = fail`. Then the generated `nabl2--transform-occurrences` are automatically picked up.

**Comment by vvergu** [comment]
I think that's a good idea. I'll make the change.

**Comment by vvergu** [comment]
Thank you

**Pull request merged**
